### PR TITLE
Add  Web Cache Deception Escalates!

### PR DESCRIPTION
**Pull request by Golim**

### CODE REVIEW

**Comment by BitnomadLive** [comment]
Hi, this paper is already on the list further down under the Web Cache topic. But I didn't have the github link to your project. Can you maybe issue a new pull request where you just add the link under the correct topic?

Edit: The paper also fits the web discovery topic (which you put it under), but I think I would prefer it to be under the Web Cache topic since I will be adding quite a few papers about web caching vulnerabilities and it is just better for people to navigate. In the future, I probably will have to split up the papers differently once I start adding papers about different other attack techniques like SQLi, request smuggling, etc

Edit2: After thinking about this for a bit I decided I will just keep the paper in both categories. Thanks for the contribution

**Comment by Golim** [comment]
Hi, thank you :+1:
I didn't see that my paper was already on the list, sorry about that

**Comment by BitnomadLive** [comment]
No worries. Are you also going to release the code for the version that allows for authenticated testing?

**Comment by Golim** [comment]
I just pushed an update that adds authenticated testing!

**Pull request merged**
